services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  admin-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # Or 'development'
    ports:
      - '3000:3000'
    depends_on:
      - elasticsearch
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_URL=http://elasticsearch:9200

volumes:
  esdata: